### PR TITLE
pause menus in other levels

### PR DESCRIPTION
**Pull request by AngelaAcquista**
added the pause menu to the other level blueprints.

### CODE REVIEW

**Comment by Trevlouw** [comment]
I just pulled this branch, what did you do to BP_SSCharacter?? I can't find it in content drawer, I'll go research this further

**Comment by Trevlouw** [comment]
Ok this branch is missing a lot of new stuff, idk how to integrate that so I'll just wait for Luis or Josh to take a look. To be honest, the best way to merge this is probably gonna be seeing what you added then moving it to master (at least I think, I'm really bad at GitHub so idk)

**Comment by AngelaAcquista** [comment]
I didn't even touch the ss character. Maybe it's because it just wasn't in the branch to begin with. The only things I added was pause menus to the other levels. I was trying to merge those things to master with this(I'm bad at Github too)

**Comment by PremiumCesium** [comment]
Looks like this branch is behind master. Try to add your changes to the most up to date version of master.

**Pull request closed without merging**
