### PR TITLE
Base Import

### PR DESCRIPTION
**Pull request by PremiumCesium**
This contains the game's basic functionalities: gamemode, player controller, level loader, camera system, respawn system, and teleportation system.

### CODE REVIEW

**Comment by Trevlouw** [comment]
Looks good, assuming nobody else tampered with stuff like Gamemode n stuff we messed with I'd imagine it'd merge perfectly, unfortunately idk how to make an approving review and the thing is telling me I'm a reviewer so idk what to do here

**Review by Trevlouw — APPROVED** [review]
I found the review button

**Comment by LuisGandora** [comment]
Looks good to me, the changes i pushed are present; area to rotate, level loader are in the branch

**Review by LuisGandora — APPROVED** [review]
Ok so my stuff; levelloader.uaasset (for loading different levels), rotatetoarea.uaasset (for camera rotation to create illusion of a 2d game) and portals.uasset are present

**Pull request merged**
